bluebonnet/bluebonnet/urls.py
from django.contrib import admin
from django.urls import include, path
#from .views import home
from . import views
from .views import MultipleModelView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', home, name='home_page'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', views.MultipleModelView.as_view(template_name='home.html'), name='home'),
    path('var_analysis/', include('var_analysis.urls')),
    path('password_change/', views.change_password, name="change_password"),
]

urlpatterns += staticfiles_urlpatterns()

bluebonnet/var_analysis/urls.py
from django.urls import path, include, re_path
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.run, name='run'),
    path('results', views.results, name='results'),
    #path('results/<int:pk>', views.QueryDetailView.as_view(), name='query-detail'),
    path('results/<int:pk>', views.EvidenceUpdateView.as_view(), name='evidence-update'),
    path('results/<gene_id>', views.GeneDetailView.as_view(), name='gene-detail'),
    re_path(r'^run-sh/$', views.run, name='run_sh'),
]

bluebonnet/var_analysis/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
import subprocess
from django.forms import ModelChoiceField
from datetime import datetime
import pytz

class Query(models.Model):
    #GENE_CHOICES =(
    #("ABCD1", "ABCD1"),
    #("ACADVL", "ACADVL"),
    #("HBB", "HBB"),)
    #gene = models.CharField(max_length=25,choices=GENE_CHOICES)
    gene = models.ForeignKey('Gene', on_delete=models.DO_NOTHING)
    var = models.CharField(max_length=25, default='')
    query_str = models.CharField(max_length=50, default='', editable = False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.CharField(max_length=25, editable = False)
    user_created = models.ForeignKey(User, editable = False, on_delete=models.DO_NOTHING, null=True, blank=True)
    user_updated = models.CharField(max_length=50, editable = False)
    latest_evidence = models.ForeignKey('Evidence', editable = False, on_delete=models.DO_NOTHING, null=True, blank=True)
    running = models.CharField(max_length=50, default='', editable = False, null=True, blank=True)

    #@property
    def __str__(self):
        return "%s:%s" % (self.gene, self.var)

    def save(self,*args,**kwargs):
        query_str_check = Query.objects.filter(query_str=self.query_str)
        if query_str_check: # if some items are found in the database
            query_str_check.update(date_updated=self.date_updated)
            query_str_check.update(user_updated=self.user_updated)
            query_str_check.update(running=self.running)
            #print(query_str_check.first().id)
            qid=list(query_str_check.values_list('id', flat=True))[0]
        else:
            return super(Query,self).save(*args,**kwargs)
        
        query_str_check.first().analysis()

    def analysis(self,*args,**kwargs):
        date_folder = "/work/NBS/outputs/" + str(self.date_updated).split()[0] + "/"
        query_prefix = str(self.gene) + "_" + str(self.id) + "_" + str(self.user_updated) + "_" + str(self.date_updated).split()[0]
        input_file = "/work/NBS/inputs/" + query_prefix + ".txt"
        latest_out = "/work/NBS/outputs/latest/" + str(self.gene) + "_" + str(self.id) + "_latest.txt"
        latest_log = "/work/NBS/outputs/latest/" + str(self.gene) + "_" + str(self.id) + "_latest.log"
        rmv_latest = "rm -f /work/NBS/outputs/latest/" + str(self.gene) + "_" + str(self.id) + "*"
        query_input_cmd = "echo '" + str(self.gene) + " " + str(self.var) + "' >|" + input_file
        #print(query_prefix)
        #print(query_input_cmd)
        #subprocess.run(['mkdir', "-p", "/work/NBS/outputs/latest/"], check=True, text=True)
        print("1")
        subprocess.run(['mkdir', "-p", date_folder], check=True, text=True)
        print("2")
        subprocess.call([query_input_cmd], shell=True)
        print("3")
        subprocess.run(['/work/NBS/runNBS.sh',input_file, str(self.date_updated), str(self.user_updated)], check=True, text=True)

class Evidence(models.Model):
    query_str = models.ForeignKey(Query, on_delete=models.CASCADE)
    norm_var = models.CharField(max_length=50, default = "N/A", null=True, blank=True)
    condition = models.CharField(max_length=50, default='')
    hgvsp = models.CharField(max_length=50, default='', editable=True)
    chrom = models.CharField(max_length=50, default='')
    start_end = models.CharField(max_length=50, default='')
    locus = models.CharField(max_length=50, default='')
    gnomad = models.TextField(max_length=10000, default='')
    dbsnp = models.TextField(max_length=10000, default='')
    clinvar = models.TextField(max_length=10000, default='')
    clinvar_id = models.CharField(max_length=50, editable = False)
    clinvar_interp = models.CharField(max_length=50, editable = False)
    clinvar_date = models.CharField(max_length=50, editable = False)
    clinvar_acc = models.CharField(max_length=50, editable = False)
    splice_sites = models.TextField(max_length=10000, default='')
    ucsc = models.CharField(max_length=10000, default='')
    polyphen2 = models.CharField(max_length=10000, default='')
    cadd = models.CharField(max_length=10000, default='')
    sift = models.CharField(max_length=10000, default='')
    provean = models.CharField(max_length=10000, default='')
    active_sites = models.TextField(max_length=10000, null=True, blank=True)
    additional_info = models.TextField(max_length=10000, null=True, blank=True)
    date_ran = models.CharField(max_length=25, editable = False)
    user = models.CharField(max_length=50, editable = False)
    rsid = models.CharField(max_length=50, editable = False)
    pubmed = models.CharField(max_length=10000, default='')
    google = models.CharField(max_length=10000, default='')
    pubsearch = models.CharField(max_length=10000, default='')

    reviewer_1 = models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name='first_reviewer', verbose_name="First Reviewer", blank=True,null=True)  
    reviewer_1_patho = models.TextField(max_length=10000, default='', blank=True,null=True)
    reviewer_1_evidence = models.TextField(max_length=10000, default='', blank=True,null=True) 
    reviewer_2 = models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name='second_reviewer', verbose_name="Second Reviewer", blank=True,null=True)  
    reviewer_2_patho = models.TextField(max_length=10000, default='', blank=True,null=True)
    reviewer_2_evidence = models.TextField(max_length=10000, default='', blank=True,null=True)
    reviewer_3 = models.ForeignKey(User,on_delete=models.DO_NOTHING,related_name='third_reviewer', verbose_name="Third Reviewer", blank=True,null=True)  
    reviewer_3_patho = models.TextField(max_length=10000, default='', blank=True,null=True)
    reviewer_3_evidence = models.TextField(max_length=10000, default='', blank=True,null=True)

    
    gnomad_evidence_category_1 = models.CharField(max_length=50, default='', blank=True,null=True)
    gnomad_evidence_category_2 = models.CharField(max_length=50, default='', blank=True,null=True)
    gnomad_evidence_category_3 = models.CharField(max_length=50, default='', blank=True,null=True)
    gnomad_comment = models.TextField(max_length=10000, default='', blank=True,null=True)
    dbsnp_patho_1 = models.CharField(max_length=50, default='', blank=True,null=True)
    dbsnp_patho_2 = models.CharField(max_length=50, default='', blank=True,null=True)
    dbsnp_patho_3 = models.CharField(max_length=50, default='', blank=True,null=True)
    dbsnp_comment = models.TextField(max_length=10000, default='', blank=True,null=True)
    clinvar_patho_1 = models.CharField(max_length=50, default='', blank=True,null=True)
    clinvar_patho_2 = models.CharField(max_length=50, default='', blank=True,null=True)
    clinvar_patho_3 = models.CharField(max_length=50, default='', blank=True,null=True)
    clinvar_comment = models.TextField(max_length=10000, default='', blank=True,null=True)
    splice_evidence_category_1 = models.CharField(max_length=50, default='', blank=True,null=True)
    splice_evidence_category_2 = models.CharField(max_length=50, default='', blank=True,null=True)
    splice_evidence_category_3 = models.CharField(max_length=50, default='', blank=True,null=True)
    splice_comment = models.TextField(max_length=10000, default='', blank=True,null=True)
    comp_evidence_category_1 = models.CharField(max_length=50, default='', blank=True,null=True)
    comp_evidence_category_2 = models.CharField(max_length=50, default='', blank=True,null=True)
    comp_evidence_category_3 = models.CharField(max_length=50, default='', blank=True,null=True)
    comp_comment = models.TextField(max_length=10000, default='', blank=True,null=True)
    active_sites_evidence_category_1 = models.CharField(max_length=50, default='', blank=True,null=True)
    active_sites_evidence_category_2 = models.CharField(max_length=50, default='', blank=True,null=True)
    active_sites_evidence_category_3 = models.CharField(max_length=50, default='', blank=True,null=True)
    active_sites_comment = models.TextField(max_length=10000, default='', blank=True,null=True)
    additional_evidence_category_1 = models.CharField(max_length=50, default='', blank=True,null=True)
    additional_evidence_category_2 = models.CharField(max_length=50, default='', blank=True,null=True)
    additional_evidence_category_3 = models.CharField(max_length=50, default='', blank=True,null=True) 
    additional_comment = models.TextField(max_length=10000, default='', blank=True,null=True)


    def __str__(self):
        return str(self.id)

class Gene(models.Model):
    gene_id = models.CharField(max_length=50, default='', primary_key = True)
    condition = models.CharField(max_length=50, default='')
    condition_site = models.CharField(max_length=1000, default='', blank=True, null=True)
    chrom = models.CharField(max_length=50, default='')
    start_end = models.CharField(max_length=100, default='')
    locus = models.CharField(max_length=50, default='')
    transcript = models.CharField(max_length=50, default='')
    np_id = models.CharField(max_length=50, default='')
    gnomad_link = models.CharField(max_length=1000, default='')
    ncbi_gene_link = models.CharField(max_length=1000, default='')

    def __str__(self):
        return str(self.gene_id)

class Reviewer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    reviewer_1 = models.BooleanField(default=False)
    reviewer_2 = models.BooleanField(default=False)
    reviewer_3 = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

bluebonnet/var_analysis/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import Query, Evidence

'''
class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for bound_field in self:
            if hasattr(bound_field, "field") and bound_field.field.required:
                bound_field.field.widget.attrs["required"] = "required"
'''
class QueryForm(forms.ModelForm):
    #def __init__(self, *args, **kwargs):
        #super(QueryForm, self).__init__(*args, **kwargs)
        #for bound_field in self:
            #print(bound_field)
            #if hasattr(bound_field, "field") and bound_field.field.required:
                #bound_field.field.widget.attrs["required"] = "required"
    
    class Meta:
        model = Query
        fields = '__all__'



class EvidenceForm(forms.ModelForm):
    widgets = {'active_sites': forms.Textarea(attrs={'rows': 100000}),}
    
    class Meta:
        model = Evidence
        fields = '__all__'

bluebonnet/var_analysis/views.py
from django.views.generic import TemplateView
from django.shortcuts import HttpResponse
from django.template import loader
from django.shortcuts import redirect, render
from django.contrib import messages
import subprocess
from django.forms import formset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.forms.widgets import Select
import os
from datetime import datetime
import glob
from .models import Query, Evidence, Gene
from .forms import QueryForm, EvidenceForm
from django.utils.safestring import mark_safe
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.utils import timezone
from django.urls import reverse
from datetime import datetime
import pytz
from django.forms.widgets import Select

def run(request):
    context = {}
    QueryFormSet = formset_factory(QueryForm, extra=0)
    formset = QueryFormSet(request.POST)
    if formset.is_valid():
        for form in formset:
            if form.is_valid():
                if form.cleaned_data != {}:
                    cd = form.cleaned_data
                    gene = cd.get('gene')
                    var = cd.get('var')
                    now = datetime.now()
                    date_fmt = now.strftime("%d%b%Y")
                    today = datetime.now(pytz.timezone('US/Central')).strftime('%Y-%m-%d %H:%M:%S')
            #file_prefix = gene + "_" + str(request.user) + "_" + date_fmt
            #print(file_prefix)
            #outfile = open("/home/klong/blah.txt", 'w')
            #subprocess.run(['echo', gene, var], check=True, text=True, stdout=outfile)
                    if gene == "" or var == "":
                        continue
                    else:
                        obj = form.save(commit=False)
                        obj.user_created = request.user
                        obj.user_updated = str(request.user)
                        obj.date_updated = today
                        obj.query_str = str(gene) + ":" + str(var)
                        obj.running = "True"
                        obj.save()
                        if obj.id == None:
                            print("Updating record...")
                        else:
                            obj.analysis()
        messages.add_message(request,
        messages.SUCCESS,
        mark_safe('Variants have been added to the queue<br/>Please check back later for results'))
        return redirect ('/var_analysis')
    else:
        formset = QueryFormSet(initial=[{'gene': '','var': ''}])
    #context['form']= form
    #return render(request, 'var_analysis/run.html', context)
    return render(request, 'var_analysis/run.html', {'formset':formset})
    #return redirect ('/var_analysis')

def results(request):
    context = {'querys': Query.objects.all()}
    return render(request, 'var_analysis/results.html', context)


class QueryDetailView(DetailView):
    model = Query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    
class EvidenceUpdateView(UpdateView):
    model = Evidence
    #fields = '__all__'
    fields = ['active_sites' ,'additional_info' ,'reviewer_1' ,'reviewer_2' ,'reviewer_3' ,'gnomad_evidence_category_1' ,'gnomad_evidence_category_2' ,'gnomad_evidence_category_3' ,'gnomad_comment','dbsnp_patho_1' ,'dbsnp_patho_2' ,'dbsnp_patho_3' ,'dbsnp_comment' ,'clinvar_patho_1' ,'clinvar_patho_2' ,'clinvar_patho_3' ,'clinvar_comment' ,'splice_evidence_category_1' ,'splice_evidence_category_2' ,'splice_evidence_category_3' ,'splice_comment' ,'comp_evidence_category_1' ,'comp_evidence_category_2' ,'comp_evidence_category_3' ,'comp_comment' ,'active_sites_evidence_category_1' ,'active_sites_evidence_category_2' ,'active_sites_evidence_category_3' ,'active_sites_comment' ,'additional_evidence_category_1' ,'additional_evidence_category_2' ,'additional_evidence_category_3' ,'additional_comment', 'reviewer_1_patho', 'reviewer_1_evidence', 'reviewer_2_patho', 'reviewer_2_evidence', 'reviewer_3_patho', 'reviewer_3_evidence']
    #success_url ="/"

    def get_success_url(self):
        pk = self.kwargs["pk"]
        # No need for reverse_lazy here, because it's called inside the method
        return reverse('evidence-update', kwargs={"pk":pk})

class GeneDetailView(DetailView):
    model = Gene
    slug_field = "gene_id"
    slug_url_kwarg = 'gene_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context



#class query_view(request, slug):
    #query_view = get_object_or_404(query, slug=slug)
    #return render(request, 'var_analysis/query_view.html', {'query_view' : query_view})

bluebonnet/var_analysis/templates/var_analysis/evidence_form.html
<!-- templates/home.html -->
{% extends 'base.html' %}


{% block content %}

<!-- INSERT FORM -->
<style>
.outputBox {
border: 2px solid black;
font: Consolas;
width: 100%;
height: 200px;
margin: 0px;
overflow-y: scroll;
z-index:-10;
}


table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 80%;
  margin-left:0;
  margin-right:auto;
}


td, th {

  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;

}

tr:nth-child(even) {

  background-color: #dddddd;

}
    .float-container {
    border: 3px solid #fff;
    padding: 20px;
	margin-bottom: 20px;
}

.float-child-left {
    width: 40%;
    float: left;
    padding: 20px;
    border: 1px solid black;
}
.float-child-right {
    width: 60%;
    float: left;
    padding: 20px;
    border: 1px solid black;
}
.float-child-left-top {
    width: 30%;
    height: 450px;
    float: left;
}
.float-child-right-top {
    width: 70%;
    height: 450px;
    float: left;
}

.inputBox {
font: Consolas;
width: 100%;
height: 200px;
margin: 0px;
z-index:-10;
}

#id_active_sites {
width:100%;
height:200px;
}
#id_additional_info {
width:100%;
height:200px;
}
#id_gnomad_comment {
width:100%;
height:170px;
}
#id_exac_comment {
width:100%;
height:170px;
}
#id_dbsnp_comment {
width:100%;
height:240px;
}
#id_clinvar_comment {
width:100%;
height:450px;
}
#id_splice_comment {
width:100%;
height:170px;
}
#id_comp_comment {
width:100%;
height:337px;
}
#id_active_sites_comment {
width:100%;
height:170px;
}
#id_additional_comment {
width:100%;
height:170px;
}
#id_reviewer_1_patho {
width:90%;
height:100px;
}
#id_reviewer_2_patho {
width:90%;
height:100px;
}
#id_reviewer_3_patho {
width:90%;
height:100px;
}
#id_reviewer_1_evidence {
width:90%;
height:100px;
}
#id_reviewer_2_evidence {
width:90%;
height:100px;
}
#id_reviewer_3_evidence {
width:90%;
height:100px;
}

.column {
float: left;
width: 25%;
}
/* The floats after the columns are cleared */
.row:after {
content: “”;
margin-left:10px;
display: table;
clear: both;
}
    .container-fluid {
margin: auto;
max-width: 80%
    }
</style>
{% for query in evidence.query_set.all %}
	{% if query.running %}
	<div style="margin-left:10px">
	<h1 style="margin-top:100px">
                <a href="/var_analysis/results/{{ query.gene }}" target="_blank" rel="noreferrer noopener">{{ query.gene }}</a>:{{ query.var }}</h1>
	<h2 style=margin-top:100px>This query is currently running. Please check back later.</h2>
	</div>
	{% else %}

<div style="margin-left:10px">
	
{% for x in evidence.query_set.all %}
	<h1 style="margin-top:100px">
		<a href="/var_analysis/results/{{ x.gene }}" target="_blank" rel="noreferrer noopener">{{ x.gene }}</a>:{{ x.var }}</h1>
{% endfor %}
</br>
<div class="float-container">

{% load static %}
<div class="float-child-left-top">

        <p><b><u>Overview:</b></u><table id="resultsTable" class="table table-striped" style="width:99%;display:inline-table;margin-right:10px">
                <tr><th>Normalized Format</th><td><pre>{{ evidence.norm_var }}</pre></td></tr>
		<tr><th>Protein Change</th><td><pre>{{ evidence.hgvsp }}</pre></td></tr>
		<tr><th>Chromosome</th><td><pre>{{ evidence.chrom }}</pre></td></tr>
		<tr><th>Positions</th><td><pre>{{ evidence.start_end }}</pre></td></tr>
		<tr><th>Date Updated</th><td><pre>{{ evidence.date_ran }}</pre></td></tr>
		<tr><th>User Updated</th><td><pre>{{ evidence.user }}</pre></td></tr>
                </table></p>
		<div style="text-align:center">
		<a href={{evidence.pubsearch}}><img src="{% static "bluebonnet/media/pubmed.png" %}" style="margin-left:5%; float:left;" width="100" height="40"></a>
		      
		<a href={{evidence.google}}><img src="{% static "bluebonnet/media/Google_Scholar_logo.png" %}" style="margin-right:5%; float:right;"  width="267" height="40"></a>
</div>
</div>


<div class="float-child-right-top">
<form method="post">
    {% csrf_token %}
    <div class=container-fluid>
    <div class=row style=margin-top:5%>
<div class=column>
	<b><u>Reviewer 1:</b></u>      </br> {{ form.reviewer_1  }}</br></br>
<b><u>Pathogenicity:</b></u>       </br>{{ form.reviewer_1_patho  }}</br></br>
<b><u>Evidence Used:</b></u>      </br>{{ form.reviewer_1_evidence  }}</div>

<div class=column>
	<b><u>Reviewer 2:</b></u>       </br>{{ form.reviewer_2  }}</br></br>
	<b><u>Pathogenicity:</b></u>      </br> {{ form.reviewer_2_patho  }}</br></br>
	<b><u>Evidence Used:</b></u>       </br>{{ form.reviewer_2_evidence  }}</div>

<div class=column>
	<b><u>Reviewer 3:</b></u>      </br> {{ form.reviewer_3  }}</br></br>
	<b><u>Pathogenicity:</b></u>       </br>{{ form.reviewer_3_patho  }}</br></br>
	<b><u>Evidence Used:</b></u>       </br>{{ form.reviewer_3_evidence  }} </div>
<div class=column>
	<button style=height:100%; type="submit">Save Updates</button>
</div>
    </div>
    </div><br>

</div>
</div>

{% load static %}
<div style="margin-top:30%"></div>   
<div class="float-container" style="margin-top:10%">

<div class="float-child-left">
		<h2>Outputs</h2>
		<b><u>Gnomad: </b></u><div class=outputBox><pre>{{ evidence.gnomad }}</pre></div></br>
    <!--<b><u>ExAC: </b></u><div class=outputBox><pre>{{ evidence.exac }}</pre></div></br>-->
    <b><u>dbSNP: </b></u>
    <table id="resultsTable" class="table table-striped" style="width:100%;display:inline-table">
                        <tr><th>RSID</th><td><pre>{{ evidence.rsid }}</pre></td></tr>
                </table>

    
    <div class=outputBox><pre>{{ evidence.dbsnp }}</pre></div></br>
                <b><u>ClinVar: </b></u>
		<table id="resultsTable" class="table table-striped" style="width:100%;display:inline-table">
			<tr><th>Variation ID</th><td><pre>{{ evidence.clinvar_id }}</pre></td></tr>
			<tr><th>Accession</th><td><pre>{{ evidence.clinvar_acc }}</pre></td></tr>
			<tr><th>Interpretation</th><td><pre>{{ evidence.clinvar_interp }}</pre></td></tr>
			<tr><th>Date Last Evaluated</th><td><pre>{{ evidence.clinvar_date }}</pre></td></tr>
					<tr><th>Link to publications</th><td><pre><a href={{evidence.pubmed}}><img src="{% static "bluebonnet/media/pubmed.png" %}" style="margin-left:5%; float:left;" width="100" height="40"></a></pre></td></tr>
		</table>
			<div class=outputBox>{{ evidence.clinvar|linebreaks }}</div></br>
                <b><u>Splice Sites: </b></u><div class=outputBox><pre>{{ evidence.splice_sites }}</pre></div></br>
                <b><u>Computational Evidence: </b></u><table id="resultsTable" class="table table-striped" style="width:100%;display:inline-table">
			<tr><th>UCSC Conservation Scores</th><td><pre>{{ evidence.ucsc }}</pre></td></tr>
			<tr><th>PolyPhen2</th><td><pre>{{ evidence.polyphen2 }}</pre></td></tr>
			<tr><th>CADD (cutoff: 20)</th><td><pre>{{ evidence.cadd }}</pre></td>
			<tr><th>SIFT (cutoff: 0.05)</th><td><pre>{{ evidence.sift }}</pre></td>
			<tr><th>PROVEAN (cutoff: -2.5)</th><td><pre>{{ evidence.provean }}</pre></td>
                </table>

{% load widget_tweaks %}
    	<b><u>Active Sites: </b></u>
		{{ form.active_sites }}
		</br></br>
	<b><u>Additional Information: </b></u>
		<div>{{ form.additional_info }}</div>
</div>

<div class="float-child-right">
	<h2>Reviews</h2>

	<div>	
	<div class=column><b><u>Evidence Category:</b></u></div>
	<div class=column>	{{ form.gnomad_evidence_category_1  }}</div>
	<div class=column>	{{ form.gnomad_evidence_category_2  }}</div>
	<div class=column>	{{ form.gnomad_evidence_category_3  }}</br></div></div>
	<b><u>Comment:</b></u>{{ form.gnomad_comment }}</br></br>

	<div>
<div class=column><b><u>Pathogenicity:</b></u></div>
<div class=column>{{ form.dbsnp_patho_1  }}</div>
<div class=column>{{ form.dbsnp_patho_2  }}</div>
<div class=column>{{ form.dbsnp_patho_3  }}</br></div></div>
<b><u>Comment:</b></u>{{ form.dbsnp_comment  }}</br></br>

</br></br><div>
<div class=column><b><u>Pathogenicity:</b></u></div>
<div class=column>	{{ form.clinvar_patho_1  }}</div>
<div class=column>	{{ form.clinvar_patho_2  }}</div>
<div class=column>	{{ form.clinvar_patho_3  }}</br></div></div>
	<b><u>Comment:</b></u>{{ form.clinvar_comment  }}</br></br>
<div>
<div class=column>        <b><u>Evidence Category:</b></u></div>
<div class=column>{{ form.splice_evidence_category_1 }}</div>
<div class=column>{{ form.splice_evidence_category_2  }}</div>
<div class=column>{{ form.splice_evidence_category_3  }}</br></div></div>
<b><u>Comment</b></u>{{ form.splice_comment  }}</br></br>
<div>
<div class=column>        <b><u>Evidence Category:</b></u></div>
<div class=column>{{ form.comp_evidence_category_1 }}</div>
<div class=column>{{ form.comp_evidence_category_2  }}</div>
<div class=column>{{ form.comp_evidence_category_3  }}</br></div></div>
<b><u>Comment:</b></u>{{ form.comp_comment  }}</br></br>
<div>
<div class=column>        <b><u>Evidence Category:</b></u></div>
<div class=column>{{ form.active_sites_evidence_category_1 }}</div>
<div class=column>{{ form.active_sites_evidence_category_2  }}</div>
<div class=column>{{ form.active_sites_evidence_category_3  }}</br></div></div>
<b><u>Comment:</b></u>{{ form.active_sites_comment  }}</br></br>
<div>
<div class=column>        <b><u>Evidence Category:</b></u></div>
<div class=column>{{ form.additional_evidence_category_1  }}</div>
<div class=column>{{ form.additional_evidence_category_2  }}</div>
<div class=column>{{ form.additional_evidence_category_3  }}</br></div></div>
<b><u>Comment:</b></u>{{ form.additional_comment  }}
</div>
</div>
</br>
</form>
{% endif %}
{% endfor %}
{% endblock %}